const endpointRoute = {
  aGlobalRoute: {
    aUnprotectedRoute: {
      aAdminHomePageRoute: "",
      bAdminAboutCompanyPageRoute: "admin-about-company-page",
      cAdminAboutApplicationPageRoute: "admin-about-application-page",
      dAdminContactPageRoute: "admin-contact-page",
      eAdminServicePageRoute: "admin-service-page",
      fAdminBranchSectionPageRoute: "admin-branch-section-page",
      gAdminBranchGroupPageRoute: "admin-branch-group-page",
      hAdminBranchPageRoute: "admin-branch-page",
      iAdminProjectSectionPageRoute: "admin-project-section-page",
      jAdminProjectGroupPageRoute: "admin-project-group-page",
      kAdminProjectPageRoute: "admin-project-page",
    },
    bProtectedRoute: {
      aAutheticatedRoute: {
        aSignInRoute: "sign-in",
        bSignUpRoute: "sign-up",
        cForgotPasswordRoute: "forgot-password",
        dResetPasswordRoute: "reset-password",
      },
      bAuthorizedRoute: {
        aTopbarRoute: {
          aAccountRetrieveRoute: "account-retrieve-primary",
          bAccountUpdateRoute: "account-update-primary",
          cAccountEmailUpdateRoute: "account-email-update-primary",
          dAccountPasswordUpdateRoute: "account-password-update-primary",
          eAccountDeleteRoute: "account-delete-primary",
        },
        bSidebarRoute: {
          aSettingRoute: {
            aBaseRoute: {
              aListRoute: "base-list",
              bCreateRoute: "base-create",
              cRetrieveRoute: "base-retrieve",
              dUpdateRoute: "base-update",
              eDeleteRoute: "base-delete",
            },
            bAPILogRoute: {
              aListRoute: "api-log-list",
              bCreateRoute: "api-log-create",
              cRetrieveRoute: "api-log-retrieve",
              dUpdateRoute: "api-log-update",
              eDeleteRoute: "api-log-delete",
            },
            cActivityLogRoute: {
              aListRoute: "activity-log-list",
              bCreateRoute: "activity-log-create",
              cRetrieveRoute: "activity-log-retrieve",
              dUpdateRoute: "activity-log-update",
              eDeleteRoute: "activity-log-delete",
            },
          },
          bUserAdministrationRoute: {
            aAccessPointRoute: {
              aListRoute: "access-point-list",
              bCreateRoute: "access-point-create",
              cRetrieveRoute: "access-point-retrieve",
              dUpdateRoute: "access-point-update",
              eDeleteRoute: "access-point-delete",
            },
            bMenuRoute: {
              aListRoute: "menu-list",
              bCreateRoute: "menu-create",
              cRetrieveRoute: "menu-retrieve",
              dUpdateRoute: "menu-update",
              eDeleteRoute: "menu-delete",
            },
            cPermissionRoute: {
              aListRoute: "permission-list",
              bCreateRoute: "permission-create",
              cRetrieveRoute: "permission-retrieve",
              dUpdateRoute: "permission-update",
              eDeleteRoute: "permission-delete",
            },
            dRoleRoute: {
              aListRoute: "role-list",
              bCreateRoute: "role-create",
              cRetrieveRoute: "role-retrieve",
              dUpdateRoute: "role-update",
              eDeleteRoute: "role-delete",
            },
            eUserRoute: {
              aListRoute: "user-list",
              bCreateRoute: "user-create",
              cRetrieveRoute: "user-retrieve",
              dUpdateRoute: "user-update",
              eDeleteRoute: "user-delete",
            },
            fProfileRoute: {
              aListRoute: "profile-list",
              bCreateRoute: "profile-create",
              cRetrieveRoute: "profile-retrieve",
              dUpdateRoute: "profile-update",
              eDeleteRoute: "profile-delete",
            },
            gAccountRoute: {
              aListRoute: "account-list",
              bCreateRoute: "account-create",
              cRetrieveRoute: "account-retrieve",
              dUpdateRoute: "account-update",
              eDeleteRoute: "account-delete",
            },
          },
          cUserAuthenticationRoute: {
            aSignInRoute: {
              aListRoute: "sign-in-list",
              bCreateRoute: "sign-in-create",
              cRetrieveRoute: "sign-in-retrieve",
              dUpdateRoute: "sign-in-update",
              eDeleteRoute: "sign-in-delete",
            },
            bSignUpRoute: {
              aListRoute: "sign-up-list",
              bCreateRoute: "sign-up-create",
              cRetrieveRoute: "sign-up-retrieve",
              dUpdateRoute: "sign-up-update",
              eDeleteRoute: "sign-up-delete",
            },
            cSignOutRoute: {
              aListRoute: "sign-out-list",
              bCreateRoute: "sign-out-create",
              cRetrieveRoute: "sign-out-retrieve",
              dUpdateRoute: "sign-out-update",
              eDeleteRoute: "sign-out-delete",
            },
            dForgotPasswordRoute: {
              aListRoute: "forgot-password-list",
              bCreateRoute: "forgot-password-create",
              cRetrieveRoute: "forgot-password-retrieve",
              dUpdateRoute: "forgot-password-update",
              eDeleteRoute: "forgot-password-delete",
            },
            eResetPasswordRoute: {
              aListRoute: "reset-password-list",
              bCreateRoute: "reset-password-create",
              cRetrieveRoute: "reset-password-retrieve",
              dUpdateRoute: "reset-password-update",
              eDeleteRoute: "reset-password-delete",
            },
          },
          dFileStorageRoute: {
            aImageStorageRoute: {
              aListRoute: "image-storage-list",
              bCreateRoute: "image-storage-create",
              cRetrieveRoute: "image-storage-retrieve",
              dUpdateRoute: "image-storage-update",
              eDeleteRoute: "image-storage-delete",
            },
            bVideoStorageRoute: {
              aListRoute: "video-storage-list",
              bCreateRoute: "video-storage-create",
              cRetrieveRoute: "video-storage-retrieve",
              dUpdateRoute: "video-storage-update",
              eDeleteRoute: "video-storage-delete",
            },
            cAudioStorageRoute: {
              aListRoute: "audio-storage-list",
              bCreateRoute: "audio-storage-create",
              cRetrieveRoute: "audio-storage-retrieve",
              dUpdateRoute: "audio-storage-update",
              eDeleteRoute: "audio-storage-delete",
            },
          },
          eContentOperationRoute: {
            aStaticContentRoute: {
              aListRoute: "static-content-list",
              bCreateRoute: "static-content-create",
              cRetrieveRoute: "static-content-retrieve",
              dUpdateRoute: "static-content-update",
              eDeleteRoute: "static-content-delete",
            },
            bSocialMediaContentRoute: {
              aListRoute: "social-media-content-list",
              bCreateRoute: "social-media-content-create",
              cRetrieveRoute: "social-media-content-retrieve",
              dUpdateRoute: "social-media-content-update",
              eDeleteRoute: "social-media-content-delete",
            },
          },
          fAdminLandingRoute: {
            aAdminHeroRoute: {
              aListRoute: "admin-hero-list",
              bCreateRoute: "admin-hero-create",
              cRetrieveRoute: "admin-hero-retrieve",
              dUpdateRoute: "admin-hero-update",
              eDeleteRoute: "admin-hero-delete",
            },
            bAdminAboutCompanyRoute: {
              aListRoute: "admin-about-company-list",
              bCreateRoute: "admin-about-company-create",
              cRetrieveRoute: "admin-about-company-retrieve",
              dUpdateRoute: "admin-about-company-update",
              eDeleteRoute: "admin-about-company-delete",
            },
            cAdminAboutApplicationRoute: {
              aListRoute: "admin-about-application-list",
              bCreateRoute: "admin-about-application-create",
              cRetrieveRoute: "admin-about-application-retrieve",
              dUpdateRoute: "admin-about-application-update",
              eDeleteRoute: "admin-about-application-delete",
            },
            dAdminContactFormRoute: {
              aListRoute: "admin-contact-form-list",
              bCreateRoute: "admin-contact-form-create",
              cRetrieveRoute: "admin-contact-form-retrieve",
              dUpdateRoute: "admin-contact-form-update",
              eDeleteRoute: "admin-contact-form-delete",
            },
            eAdminContactInfoRoute: {
              aListRoute: "admin-contact-info-list",
              bCreateRoute: "admin-contact-info-create",
              cRetrieveRoute: "admin-contact-info-retrieve",
              dUpdateRoute: "admin-contact-info-update",
              eDeleteRoute: "admin-contact-info-delete",
            },
            fAdminCounterRoute: {
              aListRoute: "admin-counter-list",
              bCreateRoute: "admin-counter-create",
              cRetrieveRoute: "admin-counter-retrieve",
              dUpdateRoute: "admin-counter-update",
              eDeleteRoute: "admin-counter-delete",
            },
            gAdminServiceRoute: {
              aListRoute: "admin-service-list",
              bCreateRoute: "admin-service-create",
              cRetrieveRoute: "admin-service-retrieve",
              dUpdateRoute: "admin-service-update",
              eDeleteRoute: "admin-service-delete",
            },
            hAdminBranchSectionRoute: {
              aListRoute: "admin-branch-section-list",
              bCreateRoute: "admin-branch-section-create",
              cRetrieveRoute: "admin-branch-section-retrieve",
              dUpdateRoute: "admin-branch-section-update",
              eDeleteRoute: "admin-branch-section-delete",
            },
            iAdminBranchGroupRoute: {
              aListRoute: "admin-branch-group-list",
              bCreateRoute: "admin-branch-group-create",
              cRetrieveRoute: "admin-branch-group-retrieve",
              dUpdateRoute: "admin-branch-group-update",
              eDeleteRoute: "admin-branch-group-delete",
            },
            jAdminBranchRoute: {
              aListRoute: "admin-branch-list",
              bCreateRoute: "admin-branch-create",
              cRetrieveRoute: "admin-branch-retrieve",
              dUpdateRoute: "admin-branch-update",
              eDeleteRoute: "admin-branch-delete",
            },
            kAdminProjectSectionRoute: {
              aListRoute: "admin-project-section-list",
              bCreateRoute: "admin-project-section-create",
              cRetrieveRoute: "admin-project-section-retrieve",
              dUpdateRoute: "admin-project-section-update",
              eDeleteRoute: "admin-project-section-delete",
            },
            lAdminProjectGroupRoute: {
              aListRoute: "admin-project-group-list",
              bCreateRoute: "admin-project-group-create",
              cRetrieveRoute: "admin-project-group-retrieve",
              dUpdateRoute: "admin-project-group-update",
              eDeleteRoute: "admin-project-group-delete",
            },
            mAdminProjectRoute: {
              aListRoute: "admin-project-list",
              bCreateRoute: "admin-project-create",
              cRetrieveRoute: "admin-project-retrieve",
              dUpdateRoute: "admin-project-update",
              eDeleteRoute: "admin-project-delete",
            },            
          },
          gFrontendLandingRoute: {
            aHeroRoute: {
              aListRoute: "hero-list",
              bCreateRoute: "hero-create",
              cRetrieveRoute: "hero-retrieve",
              dUpdateRoute: "hero-update",
              eDeleteRoute: "hero-delete",
            },
            bAboutCompanyRoute: {
              aListRoute: "about-company-list",
              bCreateRoute: "about-company-create",
              cRetrieveRoute: "about-company-retrieve",
              dUpdateRoute: "about-company-update",
              eDeleteRoute: "about-company-delete",
            },
            cAboutApplicationRoute: {
              aListRoute: "about-application-list",
              bCreateRoute: "about-application-create",
              cRetrieveRoute: "about-application-retrieve",
              dUpdateRoute: "about-application-update",
              eDeleteRoute: "about-application-delete",
            },
            dContactFormRoute: {
              aListRoute: "contact-form-list",
              bCreateRoute: "contact-form-create",
              cRetrieveRoute: "contact-form-retrieve",
              dUpdateRoute: "contact-form-update",
              eDeleteRoute: "contact-form-delete",
            },
            eContactInfoRoute: {
              aListRoute: "contact-info-list",
              bCreateRoute: "contact-info-create",
              cRetrieveRoute: "contact-info-retrieve",
              dUpdateRoute: "contact-info-update",
              eDeleteRoute: "contact-info-delete",
            },
            fCounterRoute: {
              aListRoute: "counter-list",
              bCreateRoute: "counter-create",
              cRetrieveRoute: "counter-retrieve",
              dUpdateRoute: "counter-update",
              eDeleteRoute: "counter-delete",
            },
            gServiceRoute: {
              aListRoute: "service-list",
              bCreateRoute: "service-create",
              cRetrieveRoute: "service-retrieve",
              dUpdateRoute: "service-update",
              eDeleteRoute: "service-delete",
            },
            hBranchSectionRoute: {
              aListRoute: "branch-section-list",
              bCreateRoute: "branch-section-create",
              cRetrieveRoute: "branch-section-retrieve",
              dUpdateRoute: "branch-section-update",
              eDeleteRoute: "branch-section-delete",
            },
            iBranchGroupRoute: {
              aListRoute: "branch-group-list",
              bCreateRoute: "branch-group-create",
              cRetrieveRoute: "branch-group-retrieve",
              dUpdateRoute: "branch-group-update",
              eDeleteRoute: "branch-group-delete",
            },
            jBranchRoute: {
              aListRoute: "branch-list",
              bCreateRoute: "branch-create",
              cRetrieveRoute: "branch-retrieve",
              dUpdateRoute: "branch-update",
              eDeleteRoute: "branch-delete",
            },
            kProjectSectionRoute: {
              aListRoute: "project-section-list",
              bCreateRoute: "project-section-create",
              cRetrieveRoute: "project-section-retrieve",
              dUpdateRoute: "project-section-update",
              eDeleteRoute: "project-section-delete",
            },
            lProjectGroupRoute: {
              aListRoute: "project-group-list",
              bCreateRoute: "project-group-create",
              cRetrieveRoute: "project-group-retrieve",
              dUpdateRoute: "project-group-update",
              eDeleteRoute: "project-group-delete",
            },
            mProjectRoute: {
              aListRoute: "project-list",
              bCreateRoute: "project-create",
              cRetrieveRoute: "project-retrieve",
              dUpdateRoute: "project-update",
              eDeleteRoute: "project-delete",
            },            
          },
          hChatManagementRoute: {
            aChatRoute: {
              aListRoute: "chat-list",
              bCreateRoute: "chat-create",
              cRetrieveRoute: "chat-retrieve",
              dUpdateRoute: "chat-update",
              eDeleteRoute: "chat-delete",
            },
            bMessageRoute: {
              aListRoute: "message-list",
              bCreateRoute: "message-create",
              cRetrieveRoute: "message-retrieve",
              dUpdateRoute: "message-update",
              eDeleteRoute: "message-delete",
            },
            cRequestRoute: {
              aListRoute: "request-list",
              bCreateRoute: "request-create",
              cRetrieveRoute: "request-retrieve",
              dUpdateRoute: "request-update",
              eDeleteRoute: "request-delete",
            },
          },

          hMainRoute: {
            aDashboardRoute: "dashboard",
          }
        }
      }
    }
  },
  zSampleRoute: {}
}

export default endpointRoute;
